# Generated by Django 3.2.8 on 2022-01-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('agency_name', models.CharField(max_length=200)),
                ('agent_code', models.IntegerField()),
                ('agent_phone_number', models.IntegerField()),
                ('agent_address', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('account_creation_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
