# Generated by Django 3.2.8 on 2022-02-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit_num', models.IntegerField()),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('license_num', models.CharField(max_length=200)),
                ('policies', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('birthdate', models.DateField(auto_now=True)),
                ('gender', models.CharField(max_length=5)),
                ('notification_status', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
