# Generated by Django 3.2.8 on 2021-12-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redAlertSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.CharField(max_length=200)),
                ('client_age', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAgent',
        ),
    ]
