# Generated by Django 3.2.8 on 2022-03-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redAlertSite', '0004_auto_20220306_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.IntegerField(default=11),
        ),
    ]
