# Generated by Django 3.2.8 on 2022-03-10 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimeautomation',
            name='date_str',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringautomation',
            name='start_date_str',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onetimeautomation',
            name='msg_body',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recurringautomation',
            name='msg_body',
            field=models.CharField(max_length=1000),
        ),
    ]
