# Generated by Django 3.2.8 on 2022-03-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220310_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimeautomation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recurringautomation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
