# Generated by Django 3.2.8 on 2022-04-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20220324_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_id', models.IntegerField(default=11)),
            ],
        ),
    ]
