# Generated by Django 3.2.8 on 2022-04-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220401_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearches',
            name='empty_field',
            field=models.IntegerField(default=1),
        ),
    ]
