# Generated by Django 3.2.8 on 2022-04-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_savedsearches_empty_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearches',
            name='empty_field',
        ),
    ]
