# Generated by Django 3.2.8 on 2022-04-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_savedsearches_empty_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsubset',
            name='empty_field',
            field=models.IntegerField(default=1),
        ),
    ]
