# Generated by Django 3.2.8 on 2022-04-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_savedsubset_empty_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
            ],
        ),
        migrations.RemoveField(
            model_name='savedsubset',
            name='empty_field',
        ),
    ]
