# Generated by Django 3.2.8 on 2022-04-04 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20220404_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAuto',
        ),
    ]
