# Generated by Django 3.2.8 on 2022-04-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_subset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedSubset',
        ),
    ]
